esphome:
  name: i2c_light_example

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  variant: esp32s3

# Enable Home Assistant API
api:
  encryption:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

ota:
  - platform: esphome
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

captive_portal:

# I2C interface for the light
i2c:
  - scl: GPIOXX
    sda: GPIOXX

# I2C Light component that is connected to the I2C bus on address 0x55
light:
  - platform: i2c_light
    name: light
    address: 0x55
    gamma_correct: 2.0
